In [4]:
import pandas as pd

rent_df = pd.read_csv("../data/processed/private_rents_clean_initial.csv")

rent_df.head()

/var/folders/lr/w4xj03s57999l3j70hd_bdlw0000gn/T/ipykernel_57836/2293330471.py:3: DtypeWarning: Columns (0: Index, 1: Rental price, 2: Index one bed, 3: Rental price one bed, 4: Index two bed, 5: Rental price two bed, 6: Index three bed, 7: Rental price three bed, 8: Index four or more bed, 9: Rental price four or more bed, 10: Index detached, 11: Rental price detached, 12: Index semidetached, 13: Rental price semidetached, 14: Index terraced, 15: Rental price terraced, 16: Index flat maisonette, 17: Rental price flat maisonette) have mixed types. Specify dtype option on import or set low_memory=False.
  rent_df = pd.read_csv("../data/processed/private_rents_clean_initial.csv")

,Time period,Area code,Area name,Region or country name,Index,Monthly change,Annual change,Rental price,Index one bed,Monthly change one bed,...,Annual change semidetached,Rental price semidetached,Index terraced,Monthly change terraced,Annual change terraced,Rental price terraced,Index flat maisonette,Monthly change flat maisonette,Annual change flat maisonette,Rental price flat maisonette
0,2015-01-01,K02000001,United Kingdom,[z],81.258259,[x],[x],910,82.339979,[x],...,[x],897,80.345118,[x],[x],893,83.26757,[x],[x],904
1,2015-02-01,K02000001,United Kingdom,[z],81.413747,0.191351,[x],912,82.53953,0.24235,...,[x],899,80.478716,0.166281,[x],894,83.457123,0.227644,[x],906
2,2015-03-01,K02000001,United Kingdom,[z],81.663685,0.306997,[x],915,82.781781,0.293496,...,[x],901,80.72993,0.312149,[x],897,83.73479,0.332706,[x],909
3,2015-04-01,K02000001,United Kingdom,[z],81.990506,0.400204,[x],918,83.232795,0.544823,...,[x],904,80.995081,0.328442,[x],900,84.194112,0.548543,[x],914
4,2015-05-01,K02000001,United Kingdom,[z],82.343646,0.430708,[x],922,83.597644,0.438349,...,[x],908,81.33684,0.421951,[x],904,84.638073,0.527307,[x],918

In [5]:
rent_df.shape

(48909, 40)

In [6]:
rent_df.columns = (
    rent_df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
    
)
rent_df.columns

Index(['time_period', 'area_code', 'area_name', 'region_or_country_name',
       'index', 'monthly_change', 'annual_change', 'rental_price',
       'index_one_bed', 'monthly_change_one_bed', 'annual_change_one_bed',
       'rental_price_one_bed', 'index_two_bed', 'monthly_change_two_bed',
       'annual_change_two_bed', 'rental_price_two_bed', 'index_three_bed',
       'monthly_change_three_bed', 'annual_change_three_bed',
       'rental_price_three_bed', 'index_four_or_more_bed',
       'monthly_change_four_or_more_bed', 'annual_change_four_or_more_bed',
       'rental_price_four_or_more_bed', 'index_detached',
       'monthly_change_detached', 'annual_change_detached',
       'rental_price_detached', 'index_semidetached',
       'monthly_change_semidetached', 'annual_change_semidetached',
       'rental_price_semidetached', 'index_terraced',
       'monthly_change_terraced', 'annual_change_terraced',
       'rental_price_terraced', 'index_flat_maisonette',
       'monthly_change_flat_maisonette', 'annual_change_flat_maisonette',
       'rental_price_flat_maisonette'],
      dtype='str')

In [12]:
rent_clean = rent_df[
    [
        "time_period",
        "area_code",
        "area_name",
        "region_or_country_name",
        "index",
        "monthly_change",
        "annual_change",
        "rental_price"
    ]
].copy()

rent_clean.head()

,time_period,area_code,area_name,region_or_country_name,index,monthly_change,annual_change,rental_price
0,2015-01-01,K02000001,United Kingdom,[z],81.258259,[x],[x],910
1,2015-02-01,K02000001,United Kingdom,[z],81.413747,0.191351,[x],912
2,2015-03-01,K02000001,United Kingdom,[z],81.663685,0.306997,[x],915
3,2015-04-01,K02000001,United Kingdom,[z],81.990506,0.400204,[x],918
4,2015-05-01,K02000001,United Kingdom,[z],82.343646,0.430708,[x],922

In [13]:
rent_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 48909 entries, 0 to 48908
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   time_period             48909 non-null  str
 1   area_code               48909 non-null  str
 2   area_name               48909 non-null  str
 3   region_or_country_name  48909 non-null  str
 4   index                   48909 non-null  object
 5   monthly_change          48909 non-null  str
 6   annual_change           48909 non-null  str
 7   rental_price            48909 non-null  object
dtypes: object(2), str(6)
memory usage: 5.6+ MB

In [14]:
rent_clean["time_period"] = pd.to_datetime(rent_clean["time_period"])

In [15]:
rent_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 48909 entries, 0 to 48908
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   time_period             48909 non-null  datetime64[us]
 1   area_code               48909 non-null  str
 2   area_name               48909 non-null  str
 3   region_or_country_name  48909 non-null  str
 4   index                   48909 non-null  object
 5   monthly_change          48909 non-null  str
 6   annual_change           48909 non-null  str
 7   rental_price            48909 non-null  object
dtypes: datetime64[us](1), object(2), str(5)
memory usage: 5.2+ MB

In [16]:
rent_clean = rent_clean.replace(["[x]", "[z]", "[c]"], pd.NA)

In [21]:
numeric_cols = [
    "index",
    "monthly_change",
    "annual_change",
    "rental_price"
]

In [22]:
for col in numeric_cols:
    rent_clean[col] = pd.to_numeric(rent_clean[col], errors='coerce')

In [23]:
rent_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 48909 entries, 0 to 48908
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   time_period             48909 non-null  datetime64[us]
 1   area_code               47813 non-null  str
 2   area_name               48909 non-null  str
 3   region_or_country_name  46854 non-null  str
 4   index                   48891 non-null  float64
 5   monthly_change          48534 non-null  float64
 6   annual_change           44607 non-null  float64
 7   rental_price            48891 non-null  float64
dtypes: datetime64[us](1), float64(4), str(3)
memory usage: 4.4 MB

In [26]:
rent_clean.isna().sum()

time_period                  0
area_code                 1096
area_name                    0
region_or_country_name    2055
index                       18
monthly_change             375
annual_change             4302
rental_price                18
dtype: int64

In [28]:
rent_clean = rent_clean.dropna(subset=["rental_price"])

In [31]:
essential_cols = [
    "time_period",
    "area_code",
    "area_name",
    "rental_price"
]

rent_clean = rent_clean.dropna(subset=essential_cols)

In [32]:
rent_clean = rent_clean.dropna(
    subset=[
        "time_period",
        "area_code",
        "area_name",
        "rental_price"
    ]
)

In [33]:
rent_clean.isna().sum()

time_period                  0
area_code                    0
area_name                    0
region_or_country_name    2053
index                        0
monthly_change             349
annual_change             4188
rental_price                 0
dtype: int64

In [34]:
rent_clean.to_csv(
    "../data/processed/private_rents_clean.csv",
    index=False
)

In [35]:
check_df = pd.read_csv("../data/processed/private_rents_clean.csv")

check_df.head()

,time_period,area_code,area_name,region_or_country_name,index,monthly_change,annual_change,rental_price
0,2015-01-01,K02000001,United Kingdom,NaN,81.258259,NaN,NaN,910.0
1,2015-02-01,K02000001,United Kingdom,NaN,81.413747,0.191351,NaN,912.0
2,2015-03-01,K02000001,United Kingdom,NaN,81.663685,0.306997,NaN,915.0
3,2015-04-01,K02000001,United Kingdom,NaN,81.990506,0.400204,NaN,918.0
4,2015-05-01,K02000001,United Kingdom,NaN,82.343646,0.430708,NaN,922.0

<h2><b>Create region-only version</b></h2>

In [36]:
region_names = [
    "United Kingdom",
    "England",
    "Wales",
    "Scotland",
    "Northern Ireland",
    "North East",
    "North West",
    "Yorkshire and The Humber",
    "East Midlands",
    "West Midlands",
    "East of England",
    "London",
    "South East",
    "South West"
]

In [37]:
rent_regions = rent_clean[rent_clean["area_name"].isin(region_names)].copy()

rent_regions.head()

,time_period,area_code,area_name,region_or_country_name,index,monthly_change,annual_change,rental_price
0,2015-01-01,K02000001,United Kingdom,NaN,81.258259,NaN,NaN,910.0
1,2015-02-01,K02000001,United Kingdom,NaN,81.413747,0.191351,NaN,912.0
2,2015-03-01,K02000001,United Kingdom,NaN,81.663685,0.306997,NaN,915.0
3,2015-04-01,K02000001,United Kingdom,NaN,81.990506,0.400204,NaN,918.0
4,2015-05-01,K02000001,United Kingdom,NaN,82.343646,0.430708,NaN,922.0

In [39]:
# Check what regions are present in the dataset
rent_regions["area_name"].unique()

<ArrowStringArray>
[          'United Kingdom',                  'England',
                    'Wales',                 'Scotland',
         'Northern Ireland',               'North East',
               'North West', 'Yorkshire and The Humber',
            'East Midlands',            'West Midlands',
          'East of England',                   'London',
               'South East',               'South West']
Length: 14, dtype: str

In [40]:
# Check the size
rent_regions.shape

(1916, 8)

In [41]:
# Save to CSV

rent_regions.to_csv(
    "../data/processed/private_rents_regions.csv",
    index=False
)